export type Project = {
  slug: string;
  name: string;
  domain: string;
  url: string;
  tagline: string;
  category: string;
  /** True if the audience materially overlaps the dev-tool crowd here (used for inline cross-promo) */
  devRelevant: boolean;
};

export const PROJECTS: Project[] = [
  {
    slug: "promptmysite",
    name: "PromptMySite",
    domain: "promptmysite.com",
    url: "https://promptmysite.com",
    tagline: "AI-powered conversational websites — visitors describe what they need; the site builds the answer with real UI components.",
    category: "SaaS",
    devRelevant: true,
  },
  {
    slug: "mooncake",
    name: "Mooncake",
    domain: "getmooncake.com",
    url: "https://getmooncake.com",
    tagline: "Personal-context AI chat that remembers your relationships — context that follows you across conversations.",
    category: "SaaS",
    devRelevant: true,
  },
  {
    slug: "fixed-and-shipped",
    name: "Fixed & Shipped",
    domain: "fixedandshipped.com",
    url: "https://fixedandshipped.com",
    tagline: "Senior full-stack engineering for production-ready prototypes — the things AI can't ship for you.",
    category: "Service",
    devRelevant: true,
  },
  {
    slug: "futureproof",
    name: "Future Proof Solutions",
    domain: "futureproofsolutions.im",
    url: "https://futureproofsolutions.im",
    tagline: "Software engineering consultancy for regulated industries.",
    category: "Consultancy",
    devRelevant: true,
  },
  {
    slug: "whatisyourconcern",
    name: "What is your concern?",
    domain: "whatisyourconcern.com",
    url: "https://whatisyourconcern.com",
    tagline: "An anonymous global record of what humanity is afraid of, on a draggable 3D globe.",
    category: "SaaS",
    devRelevant: false,
  },
  {
    slug: "cariadletters",
    name: "Cariad Letters",
    domain: "cariadletters.com",
    url: "https://cariadletters.com",
    tagline: "A private, custom-designed keepsake website for couples — generated by AI from photos and words.",
    category: "SaaS",
    devRelevant: false,
  },
  {
    slug: "rugbyunlocked",
    name: "Rugby Unlocked",
    domain: "rugbyunlocked.com",
    url: "https://rugbyunlocked.com",
    tagline: "Global rugby recruitment marketplace.",
    category: "Platform",
    devRelevant: false,
  },
  {
    slug: "rugbycv",
    name: "Rugby CV",
    domain: "rugbyunlocked.com",
    url: "https://rugbyunlocked.com",
    tagline: "Computer vision pipeline for automated rugby match analysis.",
    category: "ML / CV",
    devRelevant: false,
  },
];

export const DEV_RELEVANT = PROJECTS.filter((p) => p.devRelevant);
